import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// automatically generated by shadcn/ui cli
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
