/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uIOayrP9r1W
 */
import { Badge } from "~/components/ui/badge"
import { CardHeader, CardContent, Card } from "~/components/ui/card"
import { RadioGroupItem, RadioGroup } from "~/components/ui/radio-group"
import { Label } from "~/components/ui/label"
import { Button } from "~/components/ui/button"

export function QuizStep() {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader className="flex items-center space-x-4">
        <h2 className="text-lg font-bold">Quiz</h2>
        <Badge>1 of 10</Badge>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <p className="text-sm font-medium">What is the capital of France?</p>
          <RadioGroup aria-labelledby="q1" defaultValue="">
            <h3 className="sr-only" id="q1">
              Question 1
            </h3>
            <div className="space-y-2">
              <Label className="flex items-center space-x-2" htmlFor="q1-a">
                <RadioGroupItem id="q1-a" value="a" />
                <span>a) London</span>
              </Label>
              <Label className="flex items-center space-x-2" htmlFor="q1-b">
                <RadioGroupItem id="q1-b" value="b" />
                <span>b) Paris</span>
              </Label>
              <Label className="flex items-center space-x-2" htmlFor="q1-c">
                <RadioGroupItem id="q1-c" value="c" />
                <span>c) Berlin</span>
              </Label>
              <Label className="flex items-center space-x-2" htmlFor="q1-d">
                <RadioGroupItem id="q1-d" value="d" />
                <span>d) Rome</span>
              </Label>
            </div>
          </RadioGroup>
        </div>
        <div className="flex items-center space-x-2">
          <Button size="sm">Next</Button>
        </div>
      </CardContent>
    </Card>
  )
}
