/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QH7CtckXneq
 */
import Link from "next/link"

export function ThankYou() {
  return (
    <div className="flex flex-col items-center space-y-4 py-8">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Thank You!</h1>
        <p className="text-gray-500 md:text-xl/relaxed dark:text-gray-400">We appreciate your participation.</p>
      </div>
      <Link
        className="inline-flex h-10 items-center justify-center rounded-md border border-neutral-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-neutral-800"
        href="#"
      >
        Take the Quiz
      </Link>
    </div>
  )
}
